export const ROLES = {
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  RECRUITER: "RECRUITER",
  CLIENT_ADMIN: "CLIENT_ADMIN",
  CLIENT_USER: "CLIENT_USER",
  CANDIDATE: "CANDIDATE",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

// Validation function
export function isValidRole(value: string): value is Role {
  return Object.values(ROLES).includes(value as Role);
}

export const PERMISSIONS = {
  MANAGE_PLATFORM_USERS: "MANAGE_PLATFORM_USERS",
  MANAGE_CLIENT_USERS: "MANAGE_CLIENT_USERS",
  MANAGE_CLIENTS: "MANAGE_CLIENTS",
  MANAGE_CAMPAIGNS: "MANAGE_CAMPAIGNS",
  VIEW_ALL_CANDIDATES: "VIEW_ALL_CANDIDATES",
  VIEW_CLIENT_CANDIDATES: "VIEW_CLIENT_CANDIDATES",
  MANAGE_CLIENT_CANDIDATES: "MANAGE_CLIENT_CANDIDATES",
  CONFIGURE_API_KEYS: "CONFIGURE_API_KEYS",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  IMPERSONATE_USERS: "IMPERSONATE_USERS",
} as const;

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  [ROLES.PLATFORM_ADMIN]: [
    PERMISSIONS.MANAGE_PLATFORM_USERS,
    PERMISSIONS.MANAGE_CLIENT_USERS,
    PERMISSIONS.MANAGE_CLIENTS,
    PERMISSIONS.MANAGE_CAMPAIGNS,
    PERMISSIONS.VIEW_ALL_CANDIDATES,
    PERMISSIONS.VIEW_CLIENT_CANDIDATES,
    PERMISSIONS.MANAGE_CLIENT_CANDIDATES,
    PERMISSIONS.CONFIGURE_API_KEYS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.IMPERSONATE_USERS,
  ],
  [ROLES.RECRUITER]: [
    PERMISSIONS.MANAGE_CAMPAIGNS,
    PERMISSIONS.VIEW_ALL_CANDIDATES,
    PERMISSIONS.VIEW_CLIENT_CANDIDATES,
    PERMISSIONS.MANAGE_CLIENT_CANDIDATES,
    PERMISSIONS.CONFIGURE_API_KEYS,
  ],
  [ROLES.CLIENT_ADMIN]: [
    PERMISSIONS.MANAGE_CLIENT_USERS,
    PERMISSIONS.MANAGE_CAMPAIGNS,
    PERMISSIONS.VIEW_CLIENT_CANDIDATES,
    PERMISSIONS.MANAGE_CLIENT_CANDIDATES,
    PERMISSIONS.CONFIGURE_API_KEYS,
  ],
  [ROLES.CLIENT_USER]: [
    PERMISSIONS.VIEW_CLIENT_CANDIDATES,
  ],
  [ROLES.CANDIDATE]: [],
};

export function hasPermission(role: Role, permission: string): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

