/**
 * ELITE Workspace Roles and Permissions
 * 
 * Roles are scoped to org units via UserOrgMembership.roleScope
 * Permissions are derived from roles and checked via ElitePolicy
 */

export const ELITE_ROLES = {
  PROGRAM_ADMIN: "PROGRAM_ADMIN",
  COACH: "COACH",
  INSTRUCTOR: "INSTRUCTOR",
  LEARNER: "LEARNER",
  LEADERSHIP: "LEADERSHIP",
} as const;

export type EliteRole = (typeof ELITE_ROLES)[keyof typeof ELITE_ROLES];

export function isValidEliteRole(value: string): value is EliteRole {
  return Object.values(ELITE_ROLES).includes(value as EliteRole);
}

export const ELITE_PERMISSIONS = {
  // Workspace access
  ACCESS_ELITE_WORKSPACE: "ACCESS_ELITE_WORKSPACE",
  
  // Cohorts
  MANAGE_COHORTS: "MANAGE_COHORTS",
  VIEW_COHORTS: "VIEW_COHORTS",
  MANAGE_ROSTER: "MANAGE_ROSTER",
  
  // Sessions
  MANAGE_SESSIONS: "MANAGE_SESSIONS",
  VIEW_SESSIONS: "VIEW_SESSIONS",
  RECORD_ATTENDANCE: "RECORD_ATTENDANCE",
  
  // Curriculum (LMS)
  MANAGE_CURRICULUM: "MANAGE_CURRICULUM",
  VIEW_CURRICULUM: "VIEW_CURRICULUM",
  
  // Enrollments
  MANAGE_ENROLLMENTS: "MANAGE_ENROLLMENTS",
  VIEW_ENROLLMENTS: "VIEW_ENROLLMENTS",
  
  // Coaching
  MANAGE_COACHING: "MANAGE_COACHING",
  VIEW_COACHING: "VIEW_COACHING",
  MANAGE_COACHING_NOTES: "MANAGE_COACHING_NOTES",
  VIEW_COACHING_NOTES: "VIEW_COACHING_NOTES",
  VIEW_PRIVATE_NOTES: "VIEW_PRIVATE_NOTES",
  
  // Assignments & Submissions
  MANAGE_ASSIGNMENTS: "MANAGE_ASSIGNMENTS",
  SUBMIT_ASSIGNMENTS: "SUBMIT_ASSIGNMENTS",
  GRADE_ASSIGNMENTS: "GRADE_ASSIGNMENTS",
  REVIEW_SUBMISSIONS: "REVIEW_SUBMISSIONS",
  VIEW_ALL_SUBMISSIONS: "VIEW_ALL_SUBMISSIONS",
  
  // Discussions
  MODERATE_DISCUSSIONS: "MODERATE_DISCUSSIONS",
  
  // Artifacts
  MANAGE_ARTIFACTS: "MANAGE_ARTIFACTS",
  VIEW_ARTIFACTS: "VIEW_ARTIFACTS",
  
  // Messaging
  SEND_ANNOUNCEMENTS: "SEND_ANNOUNCEMENTS",
  SEND_MESSAGES: "SEND_MESSAGES",
  
  // Tasks
  MANAGE_TASKS: "MANAGE_TASKS",
  VIEW_TASKS: "VIEW_TASKS",
  
  // Analytics
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  VIEW_COHORT_ANALYTICS: "VIEW_COHORT_ANALYTICS",
  VIEW_CROSS_COHORT_ANALYTICS: "VIEW_CROSS_COHORT_ANALYTICS",
  EXPORT_ANALYTICS: "EXPORT_ANALYTICS",
  
  // Admin
  MANAGE_ELITE_CONFIG: "MANAGE_ELITE_CONFIG",
  MANAGE_PROGRAM_TEMPLATES: "MANAGE_PROGRAM_TEMPLATES",
} as const;

export type ElitePermission = (typeof ELITE_PERMISSIONS)[keyof typeof ELITE_PERMISSIONS];

/**
 * Role-Permission Matrix
 * Defines which permissions each role has
 */
export const ELITE_ROLE_PERMISSIONS: Record<EliteRole, ElitePermission[]> = {
  [ELITE_ROLES.PROGRAM_ADMIN]: [
    ELITE_PERMISSIONS.ACCESS_ELITE_WORKSPACE,
    ELITE_PERMISSIONS.MANAGE_COHORTS,
    ELITE_PERMISSIONS.VIEW_COHORTS,
    ELITE_PERMISSIONS.MANAGE_ROSTER,
    ELITE_PERMISSIONS.MANAGE_SESSIONS,
    ELITE_PERMISSIONS.VIEW_SESSIONS,
    ELITE_PERMISSIONS.RECORD_ATTENDANCE,
    // Curriculum
    ELITE_PERMISSIONS.MANAGE_CURRICULUM,
    ELITE_PERMISSIONS.VIEW_CURRICULUM,
    ELITE_PERMISSIONS.MANAGE_ENROLLMENTS,
    ELITE_PERMISSIONS.VIEW_ENROLLMENTS,
    // Coaching
    ELITE_PERMISSIONS.MANAGE_COACHING,
    ELITE_PERMISSIONS.VIEW_COACHING,
    ELITE_PERMISSIONS.MANAGE_COACHING_NOTES,
    ELITE_PERMISSIONS.VIEW_COACHING_NOTES,
    ELITE_PERMISSIONS.VIEW_PRIVATE_NOTES,
    // Assignments & Submissions
    ELITE_PERMISSIONS.MANAGE_ASSIGNMENTS,
    ELITE_PERMISSIONS.GRADE_ASSIGNMENTS,
    ELITE_PERMISSIONS.REVIEW_SUBMISSIONS,
    ELITE_PERMISSIONS.VIEW_ALL_SUBMISSIONS,
    // Discussions
    ELITE_PERMISSIONS.MODERATE_DISCUSSIONS,
    // Artifacts
    ELITE_PERMISSIONS.MANAGE_ARTIFACTS,
    ELITE_PERMISSIONS.VIEW_ARTIFACTS,
    // Messaging
    ELITE_PERMISSIONS.SEND_ANNOUNCEMENTS,
    ELITE_PERMISSIONS.SEND_MESSAGES,
    // Tasks
    ELITE_PERMISSIONS.MANAGE_TASKS,
    ELITE_PERMISSIONS.VIEW_TASKS,
    // Analytics
    ELITE_PERMISSIONS.VIEW_ANALYTICS,
    ELITE_PERMISSIONS.VIEW_COHORT_ANALYTICS,
    ELITE_PERMISSIONS.VIEW_CROSS_COHORT_ANALYTICS,
    ELITE_PERMISSIONS.EXPORT_ANALYTICS,
    // Admin
    ELITE_PERMISSIONS.MANAGE_ELITE_CONFIG,
    ELITE_PERMISSIONS.MANAGE_PROGRAM_TEMPLATES,
  ],
  
  [ELITE_ROLES.COACH]: [
    ELITE_PERMISSIONS.ACCESS_ELITE_WORKSPACE,
    ELITE_PERMISSIONS.VIEW_COHORTS,
    ELITE_PERMISSIONS.VIEW_SESSIONS,
    ELITE_PERMISSIONS.RECORD_ATTENDANCE,
    // Curriculum
    ELITE_PERMISSIONS.VIEW_CURRICULUM,
    ELITE_PERMISSIONS.VIEW_ENROLLMENTS,
    // Coaching
    ELITE_PERMISSIONS.MANAGE_COACHING,
    ELITE_PERMISSIONS.VIEW_COACHING,
    ELITE_PERMISSIONS.MANAGE_COACHING_NOTES,
    ELITE_PERMISSIONS.VIEW_COACHING_NOTES,
    ELITE_PERMISSIONS.VIEW_PRIVATE_NOTES, // Own notes only - enforced in policy
    // Assignments & Submissions
    ELITE_PERMISSIONS.REVIEW_SUBMISSIONS,
    ELITE_PERMISSIONS.VIEW_ALL_SUBMISSIONS,
    // Discussions
    ELITE_PERMISSIONS.MODERATE_DISCUSSIONS,
    // Artifacts
    ELITE_PERMISSIONS.VIEW_ARTIFACTS,
    // Messaging
    ELITE_PERMISSIONS.SEND_MESSAGES,
    // Tasks
    ELITE_PERMISSIONS.MANAGE_TASKS,
    ELITE_PERMISSIONS.VIEW_TASKS,
    // Analytics
    ELITE_PERMISSIONS.VIEW_ANALYTICS,
    ELITE_PERMISSIONS.VIEW_COHORT_ANALYTICS,
  ],
  
  [ELITE_ROLES.INSTRUCTOR]: [
    ELITE_PERMISSIONS.ACCESS_ELITE_WORKSPACE,
    ELITE_PERMISSIONS.VIEW_COHORTS,
    ELITE_PERMISSIONS.MANAGE_SESSIONS,
    ELITE_PERMISSIONS.VIEW_SESSIONS,
    ELITE_PERMISSIONS.RECORD_ATTENDANCE,
    // Curriculum
    ELITE_PERMISSIONS.VIEW_CURRICULUM,
    ELITE_PERMISSIONS.VIEW_ENROLLMENTS,
    // Assignments & Submissions
    ELITE_PERMISSIONS.MANAGE_ASSIGNMENTS,
    ELITE_PERMISSIONS.GRADE_ASSIGNMENTS,
    ELITE_PERMISSIONS.REVIEW_SUBMISSIONS,
    ELITE_PERMISSIONS.VIEW_ALL_SUBMISSIONS,
    // Discussions
    ELITE_PERMISSIONS.MODERATE_DISCUSSIONS,
    // Artifacts
    ELITE_PERMISSIONS.MANAGE_ARTIFACTS,
    ELITE_PERMISSIONS.VIEW_ARTIFACTS,
    // Messaging
    ELITE_PERMISSIONS.SEND_ANNOUNCEMENTS,
    ELITE_PERMISSIONS.SEND_MESSAGES,
    // Tasks
    ELITE_PERMISSIONS.VIEW_TASKS,
    // Analytics
    ELITE_PERMISSIONS.VIEW_ANALYTICS,
    ELITE_PERMISSIONS.VIEW_COHORT_ANALYTICS,
  ],
  
  [ELITE_ROLES.LEARNER]: [
    ELITE_PERMISSIONS.ACCESS_ELITE_WORKSPACE,
    ELITE_PERMISSIONS.VIEW_COHORTS,
    ELITE_PERMISSIONS.VIEW_SESSIONS,
    // Curriculum
    ELITE_PERMISSIONS.VIEW_CURRICULUM,
    // Assignments & Submissions
    ELITE_PERMISSIONS.SUBMIT_ASSIGNMENTS,
    // Artifacts
    ELITE_PERMISSIONS.VIEW_ARTIFACTS,
    // Messaging
    ELITE_PERMISSIONS.SEND_MESSAGES,
    // Tasks
    ELITE_PERMISSIONS.VIEW_TASKS,
  ],
  
  [ELITE_ROLES.LEADERSHIP]: [
    ELITE_PERMISSIONS.ACCESS_ELITE_WORKSPACE,
    ELITE_PERMISSIONS.VIEW_COHORTS,
    ELITE_PERMISSIONS.VIEW_SESSIONS,
    // Curriculum
    ELITE_PERMISSIONS.VIEW_CURRICULUM,
    ELITE_PERMISSIONS.VIEW_ENROLLMENTS,
    // Coaching (Read-only)
    ELITE_PERMISSIONS.VIEW_COACHING,
    ELITE_PERMISSIONS.VIEW_COACHING_NOTES,
    // Artifacts
    ELITE_PERMISSIONS.VIEW_ARTIFACTS,
    // Tasks
    ELITE_PERMISSIONS.VIEW_TASKS,
    // Analytics
    ELITE_PERMISSIONS.VIEW_ANALYTICS,
    ELITE_PERMISSIONS.VIEW_COHORT_ANALYTICS,
    ELITE_PERMISSIONS.VIEW_CROSS_COHORT_ANALYTICS,
    ELITE_PERMISSIONS.EXPORT_ANALYTICS,
  ],
};

/**
 * Check if a role has a specific permission
 */
export function hasElitePermission(role: EliteRole, permission: ElitePermission): boolean {
  const permissions = ELITE_ROLE_PERMISSIONS[role];
  return permissions?.includes(permission) ?? false;
}

/**
 * Get all permissions for a role
 */
export function getElitePermissions(role: EliteRole): ElitePermission[] {
  return ELITE_ROLE_PERMISSIONS[role] ?? [];
}

